name: Daily Update QB Tracker

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * *" # 每天 UTC 中午12点

jobs:
  update-trackers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl netcat-openbsd npm
          npm install -g wscat

      - name: Download tracker sources
        run: |
          curl -sSL https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt > trackers_temp.txt
          curl -sSL https://raw.githubusercontent.com/XIU2/TrackersListCollection/master/all.txt >> trackers_temp.txt
          curl -sSL https://raw.githubusercontent.com/hezhijie0327/Trackerslist/main/trackerslist_tracker.txt >> trackers_temp.txt
          curl -sSL "https://api.yaozuopan.top:88/composite?key=bt&auth=3cae9a3a53f1daef137126648a535ab7" >> trackers_temp.txt

      - name: Format trackers
        run: |
          bash format.sh trackers_temp.txt
          sort -u formatted_trackers.txt > qb_trackers_all.txt
          rm -f trackers_temp.txt formatted_trackers.txt

      - name: Test tracker availability
        run: bash test_trackers.sh qb_trackers_all.txt

      - name: Commit and push changes
        run: |
          echo "$(date +'%Y-%m-%d')" > date.txt
          git config --global user.email "action@gitea.local"
          git config --global user.name "Gitea Action"
          git add qb_trackers_all.txt date.txt qb_trackers_best.txt
          git commit -m "Update trackers: $(date +'%Y-%m-%d')" || echo "No changes"
          git push origin HEAD
